# Read, manipulate, and write data

   The **arcgisbinding** package provides functionality that simplifies bringing ArcGIS data types into R and manipulating them so they are ready for analysis. On the simplest level, the bridge allows for the easy transfer of data back and forth between ArcGIS and R without having to manually convert data sets into a recognizable format. However, the functionality enables much more, everything from advanced data aggregations, subsets, and selections, to data manipulations regarding format or projections. All of this contained within a couple of functions to make the process simple. Through the power of the R-ArcGIS Bridge, you can easily transfer data from ArcGIS to R to gain access to the wealth of statistical packages and functions that you might need to further your analysis. Once finished, the bridge allows you to transfer your data back to ArcGIS to take advantage of the mapping, publishing, and sharing aspects of ArcGIS. 

See below for the various topics pertaining to **arcgisbinding** package functionality. Each topic has a section containing details on how the functionality works along with practice examples. 

 - Read: [Reading ArcGIS Data Into R](#Read:-Reading-ArcGIS-Data-Into-R)
  - [arc.open Functionality](#arc.open-Functionality)    
  - [Practice Session: Read](#Practice-Session:-Read)
 - Manipulate: [Manipulating ArcGIS Data In R](#Manipulate:-Manipulating-ArcGIS-Data-In-R)
  - [Vector Data](#Vector-Data)
    - [arc.select Functionality](#arc.select-Functionality)
       - [Column Selections](#Column-Selections)
       - [Data Subsets With SQL Queries](#Data-Subsets-With-SQL-Queries)
       - [Reprojecting](#Reprojecting)
    - [arc.data2sp Functionality](#arc.data2sp-Functionality)
    - [arc.data2sf Functionality](#arc.data2sf-Functionality)
    - [Practice Session: Vector Manipulations](#Practice-Session:-Vector-Manipulations)
  - [Raster Data](#Raster-Data)
    - [arc.raster Functionality](#arc.raster-Functionality)
       - [Pixel Selections](#Pixel-Selections)
       - [Pixel Type Adjustments](#Pixel-Type-Adjustments)
       - [Resampling](#Resampling)
       - [Reprojecting](#Reprojecting)
    - [as.raster Functionality](#as.raster-Functionality)
    - [Mosaic Datasets](#Mosaic-Datasets)
    - [Practice Session: Raster Manipulations](#Practice-Session:-Raster-Manipulations)
 - Write: [Writing R Data Into ArcGIS](#Write:-Writing-R-Data-Into-ArcGIS)
    - [arc.write Functionality](#arc.write-Functionality)    
    - [Practice Session: Write](#Practice-Session:-Write)
 - Delete: [Remove and Replace Data](#Delete:-Remove-and-Replace-Data)
    - [arc.delete Functionality](#arc.delete-Functionality)    
    - [Practice Session: Delete](#Practice-Session:-Delete)
 - [Exercise: Analyze Crime Using Statistics and the R-ArcGIS Bridge](#Exercise:-Analyze-Crime-Using-Statistics-and-the-R-ArcGIS-Bridge)

 ## Read: Reading ArcGIS Data Into R
 
 The first main use of the bridge is to transfer data from ArcGIS to R. When you are first getting started with the bridge, the functions that you will use most often include:

 * `arc.check_product()`
 
 * `arc.open()`
 
Once you have initialized the bridge connection in ArcGIS by installing the **arcgisbinding** package into your R workspace, see the R-bridge-install-and-setup Jupyter Notebook for full details, you will finalize the connection between ArcGIS and R by using the `arc.check_product()` function. This function does not take any arguments and will return details regarding your current ArcGIS installation and your current version of the **arcgisbinding** package. 

```R
arc.check_product()
```

When starting a new R session or script, you will always begin with the following:

In [1]:
library(arcgisbinding)
arc.check_product()

Warning message:
"package 'arcgisbinding' was built under R version 3.5.0"*** Please call arc.check_product() to define a desktop license.


product: ArcGIS Pro ( 12.2.0.12813 )
license: Advanced 
version: 1.0.1.230

After you have successfully connected ArcGIS and R, you can begin loading your data into your desired workspace. For GIS data that is currently stored in a shapefile, file geodatabase, table, feature service, or ArcGIS supported raster data type, you will begin by using the `arc.open()` function to read it into R. 
 
 ### arc.open Functionality
 
 The Jupyter Notebooks for this preconference come with sample data which, we will use for the purpose of demonstrating the functions contained in the **arcgisbinding** package in the following tutorials. Most of this data has been stored in a file geodatabase called 'data.gdb' which is contained in a folder called 'data' along with some shapefiles. This same data will be provided for you practice with in R or RStudio during the hands-on portion of this preconference. To access this data in these notebooks, we can start by checking where our current working directory is located by using the `getwd()` core R function. This function returns the path of our working directory and comes with the core packages included with R by default. 
 

In [3]:
getwd()

[1] "C:/ArcGIS/Pro/bin/Python/envs/arcgispro-r"

Our working environment is set to the file path pertaining to a conda environment created for this Jupyter Notebook. This environment contains R and all the packages we will use throughout most of our exercises. The 'data' folder is located at this location as well. So to access data from it, we simply need to provide that folder information in our R function calls. We can check this out by inspecting the items contained in this location. 

In [4]:
list.files(path = "data")

[1] "crashes_per_mile.CPG"     "crashes_per_mile.dbf"    
[3] "crashes_per_mile.prj"     "crashes_per_mile.sbn"    
[5] "crashes_per_mile.sbx"     "crashes_per_mile.shp"    
[7] "crashes_per_mile.shp.xml" "crashes_per_mile.shx"    
[9] "data.gdb"

Now that we have a better idea of where the data for these notebooks is located, we can begin taking advantage of bridge functionality. To use the `arc.open()` function, the only argument needed is the path location at which the data you are trying to load is stored. In this case, that absolute path is `'C:/ArcGIS/Pro/bin/Python/envs/arcgispro-r/data'` for any ArcGIS shapefiles or `'C:/ArcGIS/Pro/bin/Python/envs/arcgispro-r/data/data.gdb'` for the datasets stored within this file geodatabase which include:
* African_Buffalo_Locations
* Billboard_Faces
* San_Francisco_Crimes
* World_Bioclimates_Study_Area_SM
* World_Distance_to_Water_Stud_SM
* World_Ecological_Facets_Stud_SM
* World_Land_Cover_Study_Area_SM
* World_Lithology_Study_Area_0_SM

If we were to start by opening the crashes_per_mile.shp in our data folder, we would begin by calling the `arc.open()` function with the relative path location of this shapefile as its argument. We do not need the absolute path in this case since our working directory is already set to `'C:/ArcGIS/Pro/bin/Python/envs/arcgispro-r/'`. 

```R
crashes_arc <- arc.open("data/crashes_per_mile.shp")
```

The sample data is now stored in the `crashes_arc` variable which is an `arc.dataset` object of class S4. This enables you to gain easy access to your data's metadata, such as its extent, a list of field names, and its geometry information.

```R
crashes_arc.dataset@extent
crashes_arc.dataset@fields
crashes_arc.dataset@shapeinfo
``` 

We see this for ourselves in this Jupyter Notebook by inserting an R code box below and executing the lines from above. 

In [2]:
crashes_arc <- arc.open("data/crashes_per_mile.shp")
crashes_arc@extent
crashes_arc@fields
crashes_arc@shapeinfo

xmin      ymin      xmax      ymax 
 230656.1 4094991.4  673579.2 4651709.2

$FID
[1] "OID"

$Shape
[1] "Geometry"

$OBJECTID
[1] "Integer"

$RouteNm
[1] "String"

$LABEL
[1] "String"

$BEG_MP
[1] "Double"

$END_MP
[1] "Double"

$DESCRIP
[1] "String"

$REGION
[1] "Integer"

$AVG_AADT
[1] "Double"

$FC_NAME
[1] "String"

$TOT_C
[1] "Integer"

$C_MI
[1] "Double"

$C_SCORE
[1] "Integer"

$PROTECTED
[1] "String"

$State_FA
[1] "String"

geometry type   : Polyline
WKT             : PROJCS["NAD_1983_UTM_Zone_12N",GEOGCS["GCS_North_American_19...
WKID            : 26912

If you wish to learn more, check out our documentation by running the following line in the R code box below:

In [27]:
?arc.open()

 ### Practice Session: Read 

The same data used in this Jupyter Notebook has been placed onto your machine for this preconference seminar. You can access this data by going to the following location `C:/data/`. To test out your understanding, open R or RStudio and select one (or multiple) of the layers stored within the `'C:/data/data.gdb'` to read in using the `arc.open()` function. 

> Note: If needed, make use of the R functions `getwd()` and `setwd()` if you wish to use relative instead of absolute paths. 

Pick from any of the following data layers:

* Vector Layers
  * African_Buffalo_Locations
  * Billboard_Faces
  * San_Francisco_Crimes

* Raster Layers
  * World_Bioclimates_Study_Area_SM
  * World_Distance_to_Water_Stud_SM
  * World_Ecological_Facets_Stud_SM
  * World_Land_Cover_Study_Area_SM
  * World_Lithology_Study_Area_0_SM

Practice in R or RStudio, and if you get stuck or want a hint, get to know your neighbor or ask one of us. The code solution for this exercise will be provided towards the end of our hands-on practice session.  

After you have successfully used the `arc.open()` function, feel free to play around with other useful R functions like `class()` or `str()` to explore different attributes about the results from the `arc.open()` function. 

> Note: If you select a raster layer to practice with, instead of looking at the extent, fields and shapeinfo of your `arc.open()` object, investigate the extent, bands, and pixel_type. Feel free to use `str()` to find other attributes to explore. 

## Manipulate: Manipulating ArcGIS Data In R

In its simplest use case, the **arcgisbinding** package can be used to establish a connection to an ArcGIS data type and then to convert that data type into a recognized R object, specifically either a data frame or a spatial data frame. However, other R packages offer similar functionality and as a result, the **arcgisbinding** package distinguishes itself by offering advanced data manipulations within its conversion functions to enable not only the easy transfer of data, but also the ability to transform your data into its desired state needed for a specific R analysis function. A variety of different options are available for vector data and for raster data. To begin, we will examine all of the bridge functionality pertaining to a vector data set. 

### Vector Data

While the `arc.open()` function works with all ArcGIS data types, whether vector or raster, to establish a connection to your desired ArcGIS data, the **arcgisbinding** package has two seperate functions for converting and manipulating data depending on the type of data you wish to bring into R. The `arc.select()` function is what is used for a vector dataset contained within any type of ArcGIS supported format be it a shapefile, file geodatabase, hosted feature layer, or table.

#### arc.select Functionality

The `arc.select` function is used to convert your data set into an R data frame object. This function also offers you the ability to choose specific attributes from your data set to work with, the ability to construct SQL queries to only bring in certain observations based on the criteria of your analysis, and can be used to reproject your data. Each one of these actions can be accomplished by taking advantage of the arguments of the `arc.select()` function. To help explore this functionality, we will cover each one in turn. 

To begin, let's start with the simplest use case. We simply wish to convert an ArcGIS vector data set into an R recognized object. In this case, after using the `arc.open()` function to establish a connection with our desired data set, we can use the `arc.select` function on the result generated from `arc.open()` to convert our data into an R data frame object. Let's take our `crashes_per_mile` shapefile as an example:

```R
crashes_arc <- arc.open("data/crashes_per_mile.shp")
crashes_df <- arc.select(crashes_arc)
```
Our `crashes_per_mile` ArcGIS shapefile is now in R as a data frame and any R function that takes a data frame as part of its arguments can now be used on it. For example, we can take a peek at the first 6 rows of this data frame in R by using the `head()` function. 

In [3]:
crashes_df <- arc.select(crashes_arc)
head(crashes_df)

FID OBJECTID RouteNm LABEL BEG_MP  END_MP 
1 0   1        I-15    0015N  88.353  94.453
2 1   2        I-215   0215P   7.697   9.216
3 2   3        SR-151  0151P   0.000   1.004
4 3   4        SR-115  0115P   7.072   8.247
5 4   5        SR-13   0013P   1.343   2.872
6 5   6        I-80    0080N 111.190 113.276
  DESCRIP                                                    REGION AVG_AADT 
1 SR 271 Paragonah                                           4      16786.667
2 SR 152 2000 East (Highland Drive)                          2      86801.667
3 Bangerter Highway via 10400 South                          2      19135.000
4 Rt turns on 6800 South - SR 156                            3       2836.667
5 SR 90 (200 S) via SR 13 (Main St) - Forest St Brigham City 1      13583.588
6 SR 202 Saltair Drive (Garfield Cutoff)                     2      22017.678
  FC_NAME                  TOT_C C_MI      C_SCORE PROTECTED  State_FA
1 Rural Interstate          35    1.915709 2       23 USC 409 State   
2 Urban Interstate         101   22.295806 4       23 USC 409 State   
3 Urban Principal Arterial  63   21.000000 4       23 USC 409 State   
4 Urban Collector           17    4.843305 3       23 USC 409 State   
5 Urban Principal Arterial  84   18.421053 4       23 USC 409 State   
6 Urban Interstate          68   10.897436 3       23 USC 409 State

The first argument of the `arc.select()` function is the resulting object from the `arc.open()` function. To simplify the above example, we could actually type the following instead:

```R
crashes_df <- arc.select(arc.open("data/crashes_per_mile.shp"))
```

This is a more efficient call since we are not wasting memory on the object from `arc.open()` which we will not use outside of being an argument to `arc.select()`. 

However, in the above example, we are not diving into what makes the **arcgisbinding** package so powerful. For starters, we are using a shapefile and we are also not opting to make any manipulations. Let's take a look at some of the more advanced functionality of `arc.select()` in detail:

##### Column Selections

The second argument to the `arc.open()` function is a parameter called `fields`. This parameter allows us to specify the specific columns from our ArcGIS data set that we wish to bring in, if we do not need all of them for our R work. To use the `fields` parameter, you will construct a vector of strings pertaining to the specific column names you wish to bring in. These column names must match those in your ArcGIS data set exactly in terms of spelling and capitalization. As a example, above, we saw the first six rows of the `crashes_per_mile` shapefile along with the column names. Say we were only interested in the columns pertaining to object id, route number, beginning milepost, ending milepost, and region. To bring in only these columns, we would construct the following `arc.select()` function call:

```R
crashes_subset_df <- arc.select(arc.open("data/crashes_per_mile.shp"), c("OBJECTID", "RouteNm", "BEG_MP", "END_MP", "REGION"))
```
We can see how this works in R below:

In [28]:
crashes_subset_df <- arc.select(arc.open("data/crashes_per_mile.shp"), c("OBJECTID", "RouteNm", "BEG_MP", "END_MP", "REGION"))
head(crashes_subset_df)

OBJECTID RouteNm BEG_MP  END_MP  REGION
1 1        I-15     88.353  94.453 4     
2 2        I-215     7.697   9.216 2     
3 3        SR-151    0.000   1.004 2     
4 4        SR-115    7.072   8.247 3     
5 5        SR-13     1.343   2.872 1     
6 6        I-80    111.190 113.276 2

##### Data Subsets With SQL Queries

The third argument of the `arc.select()` function allows us to specify an SQL query if we wish to make a subset of our data based on a certain attribute value. This parameter is called the `where_clause` and it can be used by putting the column name that contains the attribute you wish to subset off of along with the expression desired and the attribute value, all in quotes. For example, if we wish to examine the subset of crashes that occurred on Route 1-80, we could craft the following `arc.select()` function call:

```R
crashes_subset_df <- arc.select(arc.open("data/crashes_per_mile.shp"), c("OBJECTID", "RouteNm", "BEG_MP", "END_MP", "REGION"), "RouteNm = 'I-80'")
```
Or, if we wished to examine the subset of crashes that occurred between regions 2 and 4 (inclusively), we could do so with the following call:

```R
crashes_subset_df <- arc.select(arc.open("data/crashes_per_mile.shp"), c("OBJECTID", "RouteNm", "BEG_MP", "END_MP", "REGION"), "REGION >= 2 AND REGION <= 4")
```

Let's try this out in R:

In [5]:
crashes_subset2_df <- arc.select(arc.open("data/crashes_per_mile.shp"), c("OBJECTID", "RouteNm", "BEG_MP", "END_MP", "REGION"), "REGION >= 2 AND REGION <= 4")
head(crashes_subset2_df)

OBJECTID RouteNm BEG_MP  END_MP  REGION
1 1        I-15     88.353  94.453 4     
2 2        I-215     7.697   9.216 2     
3 3        SR-151    0.000   1.004 2     
4 4        SR-115    7.072   8.247 3     
5 6        I-80    111.190 113.276 2     
6 7        I-15    297.920 298.916 2

##### Reprojecting

The fourth argument of the `arc.select` function allows us to reproject our data by using the `sr` parameter and specifying either the ESPG reference number or the WKT or proj4 associcated with the ESPG reference number for the desired projection. Our `crashes_per_mile` shapefile is currently projected in the [UTM Zone 12N](http://spatialreference.org/ref/epsg/nad83-utm-zone-12n/). However, for the sake of demonstration only, say we wished to reproject into [NAD27 Utah Central](http://spatialreference.org/ref/epsg/32043/). We could do so in one of the following ways:

ESPG reference number

```R
crashes_subset3_df <- arc.select(arc.open("data/crashes_per_mile.shp"), c("OBJECTID", "RouteNm", "BEG_MP", "END_MP", "REGION"), "REGION >= 2 AND REGION <= 4", sr = 32043)
```

Esri WKT

```R
crashes_subset3_df <- arc.select(arc.open("data/crashes_per_mile.shp"), c("OBJECTID", "RouteNm", "BEG_MP", "END_MP", "REGION"), "REGION >= 2 AND REGION <= 4", sr = 'PROJCS["NAD27 / Utah Central",GEOGCS["GCS_North_American_1927",DATUM["D_North_American_1927",SPHEROID["Clarke_1866",6378206.4,294.9786982138982]],PRIMEM["Greenwich",0],UNIT["Degree",0.017453292519943295]],PROJECTION["Lambert_Conformal_Conic"],PARAMETER["standard_parallel_1",39.01666666666667],PARAMETER["standard_parallel_2",40.65],PARAMETER["latitude_of_origin",38.33333333333334],PARAMETER["central_meridian",-111.5],PARAMETER["false_easting",2000000],PARAMETER["false_northing",0],UNIT["Foot_US",0.30480060960121924]]')
```

proj4 string

```R
crashes_subset3_df <- arc.select(arc.open("data/crashes_per_mile.shp"), c("OBJECTID", "RouteNm", "BEG_MP", "END_MP", "REGION"), "REGION >= 2 AND REGION <= 4", sr = '+proj=lcc +lat_1=39.01666666666667 +lat_2=40.65 +lat_0=38.33333333333334 +lon_0=-111.5 +x_0=609601.2192024384 +y_0=0 +ellps=clrk66 +datum=NAD27 +to_meter=0.3048006096012192 +no_defs')

```

We can test all of these out in the R console:

In [6]:
#Original data
crashes_subset3_df <- arc.select(arc.open("data/crashes_per_mile.shp"), c("OBJECTID", "RouteNm", "BEG_MP", "END_MP", "REGION"), "REGION >= 2 AND REGION <= 4")
arc.shape(crashes_subset3_df)

#ESPG reference number
crashes_subset3_df <- arc.select(arc.open("data/crashes_per_mile.shp"), c("OBJECTID", "RouteNm", "BEG_MP", "END_MP", "REGION"), "REGION >= 2 AND REGION <= 4", sr = 32043)
arc.shape(crashes_subset3_df)

#WKT
crashes_subset3_df <- arc.select(arc.open("data/crashes_per_mile.shp"), c("OBJECTID", "RouteNm", "BEG_MP", "END_MP", "REGION"), "REGION >= 2 AND REGION <= 4", sr = 'PROJCS["NAD27 / Utah Central",GEOGCS["GCS_North_American_1927",DATUM["D_North_American_1927",SPHEROID["Clarke_1866",6378206.4,294.9786982138982]],PRIMEM["Greenwich",0],UNIT["Degree",0.017453292519943295]],PROJECTION["Lambert_Conformal_Conic"],PARAMETER["standard_parallel_1",39.01666666666667],PARAMETER["standard_parallel_2",40.65],PARAMETER["latitude_of_origin",38.33333333333334],PARAMETER["central_meridian",-111.5],PARAMETER["false_easting",2000000],PARAMETER["false_northing",0],UNIT["Foot_US",0.30480060960121924]]')
arc.shape(crashes_subset3_df)

#proj4
crashes_subset3_df <- arc.select(arc.open("data/crashes_per_mile.shp"), c("OBJECTID", "RouteNm", "BEG_MP", "END_MP", "REGION"), "REGION >= 2 AND REGION <= 4", sr = '+proj=lcc +lat_1=39.01666666666667 +lat_2=40.65 +lat_0=38.33333333333334 +lon_0=-111.5 +x_0=609601.2192024384 +y_0=0 +ellps=clrk66 +datum=NAD27 +to_meter=0.3048006096012192 +no_defs')
arc.shape(crashes_subset3_df)

geometry type   : Polyline
WKT             : PROJCS["NAD_1983_UTM_Zone_12N",GEOGCS["GCS_North_American_19...
WKID            : 26912
length          : 2820 

geometry type   : Polyline
WKT             : PROJCS["NAD_1927_StatePlane_Utah_Central_FIPS_4302",GEOGCS["...
WKID            : 32043
length          : 2820 

geometry type   : Polyline
WKT             : PROJCS["NAD27 / Utah Central",GEOGCS["GCS_North_American_192...
length          : 2820 

geometry type   : Polyline
WKT             : PROJCS["Lambert_Conformal_Conic_2SP",GEOGCS["GCS_North_Ameri...
length          : 2820 

In addition to `arc.select()` functionality which converts your ArcGIS data to an R data frame object, the bridge also offers functions to convert your data from an R data frame object to a corresponding spatial data frame object from the R package **sp** or R package **sf**. These functions are useful if you plan to perform some type of spatial analysis in R and need your data in a recognized spatial object. 

#### arc.data2sp Functionality

To convert from an R data frame to an **sp** package spatial data frame, simply run the `arc.data2sp()` function on the resulting data frame from your `arc.select()` function call. The R vignette on the **sp** package can be found [here](https://cran.r-project.org/web/packages/sp/vignettes/intro_sp.pdf). 

```R
crashes_subset2_spdf <- arc.data2sp(crashes_subset2_df)

```

#### arc.data2sf Functionality

To convert from an R data frame to an **sf** package spatial data frame, simply run the `arc.data2sp()` function on the resulting data frame from your `arc.select()` function call. The R vignette on the **sf** package can be found [here](https://cran.r-project.org/web/packages/sf/vignettes/sf1.html). 

```R
crashes_subset2_sfdf <- arc.data2sf(crashes_subset2_df)
```

Test out how these functions work in the R console below:

In [7]:
class(crashes_subset2_df)

crashes_subset2_spdf <- arc.data2sp(crashes_subset2_df)
class(crashes_subset2_spdf)

crashes_subset2_sfdf <- arc.data2sf(crashes_subset2_df)
class(crashes_subset2_sfdf)

[1] "arc.data"   "data.frame"

[1] "SpatialLinesDataFrame"
attr(,"package")
[1] "sp"

[1] "sf"         "data.frame"

#### Practice Session: Vector Manipulations

In R or RStudio, test out your understanding by selecting one (or multiple) of the vector layers stored within `'C:/data/data.gdb'` to practice using the `arc.select()` function. You can pick from any of the following:

* Vector Layers
  * African_Buffalo_Locations
  * Billboard_Faces
  * San_Francisco_Crimes

Practice in R or RStudio, and if you get stuck or want a hint, get to know your neighbor or ask one of us. The code solution for this exercise will be provided towards the end of our hands-on practice session. 

If you are looking for an idea, start by trying the following on San_Francisco_Crimes:
* Craft an `arc.select()` function call to only bring in the columns OBJECTID, Dates, Category, DayOfWeek, PdDistrict, and Address columns. 
* Craft an `arc.select()` function call to select only rows pertaining to a crime of Category 'ASSAULT'. 
* Craft an `arc.select()` function call to reproject the R data frame for your San_Francisco_Crimes data to [ESPG: 2227](http://spatialreference.org/ref/epsg/2227/)

### Raster Data

The R-ArcGIS bridge recently expanded its capabilities to include working with raster data. This means that the **arcgisbinding** package has been updated to include some new functions specific for manipulating and converting ArcGIS raster layers into R recognized raster objects (from the R package **raster**). If you have an older version of the bridge, you will need to update your **arcgisbinding** package in order to access this functionality. For information on how to do so, see the section on upgrading the **arcgisbinding** package in the Jupyter Notebook R-bridge-install-and-setup. 

#### arc.raster Functionality

While the `arc.open()` function works with all ArcGIS data types, whether vector or raster, to establish a connection to your desired ArcGIS data, the **arcgisbinding** package has seperate functions for converting and manipulating data depending on the type of data you wish to bring into R. The `arc.raster()` function is what is used for converting and manipulating a raster layer contained within any type of ArcGIS supported format before finishing the conversion process into R using the `as.raster()` function. 

To begin, let's start with the simplest use case. We simply wish to convert an ArcGIS raster layer into an R recognized raster object. In this case, after using the `arc.open()` function to establish a connection with our desired data set, we can use the `arc.raster()` function on the result generated from `arc.open()`, followed by the `as.raster()` function, to convert our data into an R raster object. If we are working with a single band, the result will be a _RasterLayer_ object. If we are working with multiple bands, the results will be a _RasterBrick_ object. Let's take our `World_Distance_to_Waster_Stud_SM` file geodatabase raster as an example:

```R
distance_to_water_ras <- as.raster(arc.raster(arc.open("data/data.gdb/World_Distance_to_Water_Stud_SM")))
```

Our `World_Distance_to_Waster_Stud_SM` file geodatabase raster is now in R as a _RasterLayer_ and any R function that takes a **raster** package object as part of its arguments can now be used on it. To check this, we can run the following line in R and check the class of the resulting object. 


In [12]:
distance_to_water_ras <- as.raster(arc.raster(arc.open("data/data.gdb/World_Distance_to_Water_Stud_SM")))
class(distance_to_water_ras)

[1] "RasterLayer"
attr(,"package")
[1] "raster"

In addition to this simplest use case shown above, the `arc.raster()` function also offers advanced manipulations for raster layers. Next, we will cover some of the additional options that exist. 

> Note: The parameter options covered here are only some of the options that exist within the `arc.raster()` function. For full options and details, please refer to the documentation on this function. 

In [ ]:
?arc.raster()

##### Pixel Selections

If you only wish to bring in a subset of pixels from your raster, you can define them using the `nrow` and `ncol` parameters of the `arc.raster()` function. This can be useful if you wish to test out R functionality on a smaller subset of your raster first, before bringing in the full raster layer into R. 

To use, simply specify the number of rows and columns you wish to bring into R. 

```R
distance_to_water_ras <- as.raster(arc.raster(arc.open("data/data.gdb/World_Distance_to_Water_Stud_SM"), nrow = 100, ncol = 100))
```

In [14]:
distance_to_water_ras <- as.raster(arc.raster(arc.open("data/data.gdb/World_Distance_to_Water_Stud_SM"), nrow = 100, ncol = 100))
dim(distance_to_water_ras)

[1] 100 100   1

##### Extent 

You can adjust the extent for the raster object you bring into R by using the `extent` parameter and specifying your desired xmax, ymax, xmin, and ymin values in a numeric vector. Order does matter here, so be mindful as you select your values. 

In the example below, we are adjusting the extent of our raster to have a xmax value of 31, a ymax value of 25.5, a xmin value of 30, and a ymin value of 24.5. 

```R
distance_to_water_ras_extent <- as.raster(arc.raster(arc.open("data/data.gdb/World_Distance_to_Water_Stud_SM"), nrow = 100, ncol = 100, extent = c(31, 25.5, 30, 24.5)))

```

We can test out the results in the R console below. 

In [15]:
#Original extent values
distance_to_water_ras <- as.raster(arc.raster(arc.open("data/data.gdb/World_Distance_to_Water_Stud_SM"), nrow = 100, ncol = 100))
distance_to_water_ras@extent

#Modified extent values
distance_to_water_ras_extent <- as.raster(arc.raster(arc.open("data/data.gdb/World_Distance_to_Water_Stud_SM"), nrow = 100, ncol = 100, extent = c(31, 25.5, 30, 24.5)))
distance_to_water_ras_extent@extent

class       : Extent 
xmin        : 30.98066 
xmax        : 32.96726 
ymin        : -25.46767 
ymax        : -24.50616 

class       : Extent 
xmin        : 30 
xmax        : 31 
ymin        : 24.5 
ymax        : 25.5 

##### Resampling

If you elect to create a subset of your original data, you might wish to resample. In which case, the `arc.select()` function offers options for resampling your data through the `resample_type` argument. 

Here, we are creating a subset of our original data by specifying a desired number of rows and columns and then resampling the subset using the Cubic Convolution method. 

```R
distance_to_water_ras <- as.raster(arc.raster(arc.open("data/data.gdb/World_Distance_to_Water_Stud_SM"), nrow = 100, ncol = 100))
```

We can explore this result in the R console below:

In [16]:
#Original Pixel Values
distance_to_water_ras <- as.raster(arc.raster(arc.open("data/data.gdb/World_Distance_to_Water_Stud_SM"), nrow = 100, ncol = 100))
head(distance_to_water_ras, 15)

#Resampled Pixel Values
distance_to_water_ras_resamp <- as.raster(arc.raster(arc.open("data/data.gdb/World_Distance_to_Water_Stud_SM"), nrow = 100, ncol = 100, resample_type="CubicConvolution"))
head(distance_to_water_ras, 15)

[1] 14 13  8  5  4  6 10 14 18 22 27 30 33 35 39

[1] 14 13  8  5  4  6 10 14 18 22 27 30 33 35 39

##### Reprojecting

Similarly to the `arc.select()` function, we can reproject our data by using the `sr` parameter and specifying either the ESPG reference number, the WKT, or proj4 associcated with the ESPG reference number for the desired projection. Our `World_Distance_to_Waster_Stud_SM` file geodatabase raster is currently not projected. If we wished to add a projection, we could do so in the following way:

ESPG reference number

```R
distance_to_water_ras <- arc.raster(arc.open("data/data.gdb/World_Distance_to_Water_Stud_SM"), nrow = 100, ncol = 100, sr = 102003)
```
By checking the value of the `sr` attribute value, we can see our spatial reference has now changed.

In [17]:
#Original Spatial Reference Information
distance_to_water_ras <- arc.raster(arc.open("data/data.gdb/World_Distance_to_Water_Stud_SM"), nrow = 100, ncol = 100)
distance_to_water_ras$sr

#ESPG reference number
distance_to_water_ras <- arc.raster(arc.open("data/data.gdb/World_Distance_to_Water_Stud_SM"), nrow = 100, ncol = 100, sr = 102003)
distance_to_water_ras$sr


$WKT
[1] "GEOGCS[\"WGS 84\",DATUM[\"World Geodetic System 1984\",SPHEROID[\"WGS 84\",6378137.0,298.257223563]],PRIMEM[\"Greenwich\",0.0],UNIT[\"degree\",0.0174532925199433]]"

$WKID
[1] 0

$WKT
[1] "PROJCS[\"USA_Contiguous_Albers_Equal_Area_Conic\",GEOGCS[\"GCS_North_American_1983\",DATUM[\"D_North_American_1983\",SPHEROID[\"GRS_1980\",6378137.0,298.257222101]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]],PROJECTION[\"Albers\"],PARAMETER[\"False_Easting\",0.0],PARAMETER[\"False_Northing\",0.0],PARAMETER[\"Central_Meridian\",-96.0],PARAMETER[\"Standard_Parallel_1\",29.5],PARAMETER[\"Standard_Parallel_2\",45.5],PARAMETER[\"Latitude_Of_Origin\",37.5],UNIT[\"Meter\",1.0]]"

$WKID
[1] 102003

#### as.raster Functionality

We have already seen the `as.raster()` function in some of the examples above, but to formally define it, the `as.raster()` function is from the R package **raster** and is designed to help create raster objects. It is utilized in the **arcgisbinding** package to help finish the conversion process from an ArcGIS raster type to an R **raster** package object. Full documentation on the function can be found [here](https://www.rdocumentation.org/packages/raster/versions/2.6-7/topics/as.raster). 

#### Practice Session: Raster Manipulations

In R or RStudio, test out your understanding by selecting one (or multiple) of the raster layers stored within `'C:/data/data.gdb'` to practice using the `arc.raster()` and `as.raster()` functions on. You can pick from any of the following:

* Raster Layers
  * World_Bioclimates_Study_Area_SM
  * World_Distance_to_Water_Stud_SM
  * World_Ecological_Facets_Stud_SM
  * World_Land_Cover_Study_Area_SM
  * World_Lithology_Study_Area_0_SM

Practice in R or RStudio, and if you get stuck or want a hint, get to know your neighbor or ask one of us. The code solution for this exercise will be provided towards the end of our hands-on practice session. 

If you are looking for an idea, start by trying the following on World_Lithology_Study_Area_0_SM:
* Craft an `arc.raster()` function call to bring in a 100 x 100 selection of the World Lithology layer. 
* Craft an `arc.raster()` function call to adjust the extent of the World Lithology Layer to have the following values: xmin:30.5, xmax:33, ymin:-25.5, ymax:-24.5. 
* Craft an `arc.raster()` function call to bring in a 100 x 100 selection of the World Lithology layer and to resample using the NearestNeighbor method. 

## Write: Writing R Data Into ArcGIS

When you are finished working in R, it is likely you will wish to transfer your results back into ArcGIS either for future analysis or to map and share the final results. In which case, the `arc.write()` function is here to help. 

### arc.write Functionality

The `arc.write()` function allows you to easily save your data to shapefile, file geodatabase, table, or supported raster data type of your choice. The first argument is the path for the location of the folder or file geodatabase you wish to write your new results to along with the file extension you want. The second argument specifies the R object you are writing to this new location. Additional optional parameters allow you to provide the geometry type and spatial reference for your data, if desired. 

In the example below, the `crashes_subset_df` object from our section on [Column Selections](#Column-Selections) is being written out to our data folder as a shapefile. This example could also easily be modified to write to a file geodatabase by changing the path to `'data/data.gdb/writing_practice'`, if desired. 

```R
arc.write("data/writing_practice.shp", crashes_subset_df)
```

The `arc.write` function has also been designed with data generation in mind. For example, the function can be used to create new features in ArcGIS as demonstrated below where the `arc.write` function creates 100 uniformly distributed points in a unit square from a normal distribution.

```R
arc.write("data/new_pts.shp", data = list('data'=rnorm(100)),
          coords = list(x=runif(100,min=0,max=1),y=runif(100,min=0,max=1)),
          shape_info = list(type='Point'))

```

After running `arc.write()` we can observe a new shapefile has been added to our data folder by using the `list.files()` function. 

In [29]:
arc.write("data/writing_practice.shp", crashes_subset_df)
list.files(path = "data")

[1] "crashes_per_mile.CPG"                          
 [2] "crashes_per_mile.dbf"                          
 [3] "crashes_per_mile.prj"                          
 [4] "crashes_per_mile.sbn"                          
 [5] "crashes_per_mile.sbx"                          
 [6] "crashes_per_mile.shp"                          
 [7] "crashes_per_mile.shp.MARJEAN.9772.9804.sr.lock"
 [8] "crashes_per_mile.shp.xml"                      
 [9] "crashes_per_mile.shx"                          
[10] "data.gdb"                                      
[11] "new_pts.cpg"                                   
[12] "new_pts.dbf"                                   
[13] "new_pts.shp"                                   
[14] "new_pts.shx"                                   
[15] "writing_practice.cpg"                          
[16] "writing_practice.dbf"                          
[17] "writing_practice.prj"                          
[18] "writing_practice.shp"                          
[19] "writing_practice.shx"

### Practice Session: Write

Test out your understanding by selecting one (or multiple) of the data sets you have been working with today to write to a location and extension of your choice. 

When practicing writing, you can pick from any of the file locations and extensions below:

* Vector Layers
  * C:/data/<insert_name_here>.shp
  * C:/data/data.gdb/<insert_name_here>


* Raster Layers
  * C:/data/<insert_name_here.tif>
  * C:/data/<insert_name_here.img>
  * ...
  * C:/data/data.gdb/<insert_name_here>
  
Practice in R or RStudio, and if you get stuck or want a hint, get to know your neighbor or ask one of us. The code solution for this exercise will be provided towards the end of our hands-on practice session. Feel free to practice writing to a path associated with an ArcMap or ArcGIS Pro project and once written, bringing that data into a map. 

> Note: If you are writing to an ArcMap or ArcGIS Pro project, make sure you refresh the folder or file geodatabase you have written to in order to view your data. 

If you are looking for an idea, start by trying to write the below R _RasterLayer_ to a location of your choice with an extension of .png:

```R
distance_to_water_ras <- as.raster(arc.raster(arc.open("data/data.gdb/World_Distance_to_Water_Stud_SM"), nrow = 100, ncol = 100))
```

## Delete: Remove and Replace Data

Occassionally, we make mistakes and create something we wish to overwrite. In these cases, you can do this by first removing your unwanted data using `arc.delete()`. 

### arc.delete Functionality

If you have generated output through the `arc.write()` function that you wish to overwrite or remove, you can use the `arc.delete()` function to either permanently delete the previously created output or to delete the old output prior to recreating it again with 'arc.write'.  

In the example above for `arc.write()`, we created the `writing_practice.shp` in our `data` folder. We can remove this file by using the `arc.delete()` function. 

```R
arc.delete("data/writing_practice.shp")

```

After running `arc.delete()` we can observe our `writing_practice` shapefile has been deleted from our data folder by using the `list.files()` function. 

In [37]:
arc.delete("data/writing_practice.shp")
list.files(path = "data")

[1] "crashes_per_mile.CPG"     "crashes_per_mile.dbf"    
 [3] "crashes_per_mile.prj"     "crashes_per_mile.sbn"    
 [5] "crashes_per_mile.sbx"     "crashes_per_mile.shp"    
 [7] "crashes_per_mile.shp.xml" "crashes_per_mile.shx"    
 [9] "data.gdb"                 "new_pts.cpg"             
[11] "new_pts.dbf"              "new_pts.shp"             
[13] "new_pts.shx"

### Practice Session: Delete

Test out your understanding by selecting one (or multiple) of the data sets you created using `arc.write()` and deleting them.  

When practicing deleting, keep in mind the location, file name, and extension you used when originally writing out the data. Some likely file locations and extensions you might have used are listed below: 

* Vector Layers
  * C:/data/<insert_name_here>.shp
  * C:/data/data.gdb/<insert_name_here>


* Raster Layers
  * C:/data/<insert_name_here.tif>
  * C:/data/<insert_name_here.img>
  * ...
  * C:/data/data.gdb/<insert_name_here>
  
Practice in R or RStudio, and if you get stuck or want a hint, get to know your neighbor or ask one of us. The code solution for this exercise will be provided towards the end of our hands-on practice session. Feel free to practice deleting a data set you wrote to a path associated with an ArcMap or ArcGIS Pro project and once deleted, checking the location inside your project's catalog pane and folder tree to ensure it is gone.  

> Note: If you are deleting a data set in a folder associated with an ArcMap or ArcGIS Pro project, make sure you refresh the folder or file geodatabase before checking if it deleted. 

If you are looking for an idea, start by trying to delete the layer created below:

```R
    #distance_to_water_ras <- as.raster(arc.raster(arc.open("data/data.gdb/World_Distance_to_Water_Stud_SM"), nrow = 100, ncol = 100))
    arc.write("C:/data/RasterTest.png", distance_to_water_ras)
```

## Exercise: Analyze Crime Using Statistics and the R-ArcGIS Bridge

To practice your understanding of how to read, convert, and write data using the **arcgisbinding** package, we will be using the learn lesson: [Analyze Crime Using Statistics and the R-ArcGIS Bridge](https://learn.arcgis.com/en/projects/analyze-crime-using-statistics-and-the-r-arcgis-bridge/). This learn lesson will walk you through a real life example of how you can use bridge functionality to simplify incorporating advanced analytics into your organization's workflows. 